app/main/forms.py
from flask_wtf import FlaskForm
from flask_babel import _, lazy_gettext as _l
from wtforms import StringField, TextAreaField, PasswordField, BooleanField, SubmitField, DateTimeField, SelectField
from wtforms.validators import DataRequired, EqualTo, ValidationError, Email, Length
from app.models import Account
from flask_login import current_user


class CreateCarForm(FlaskForm):
    brand = StringField(_l('Car brand'), validators=[DataRequired()])
    model = StringField(_l('Car model'), validators=[DataRequired()])
    color = StringField(_l('Car color'), validators=[DataRequired()])
    submit = SubmitField(_l('Create car'))


class EditProfileForm(FlaskForm):
    username = StringField(_l('Username'))
    email = StringField(_l('Email'))
    about_me = TextAreaField(_l('About me'), validators=[
                             Length(min=0, max=140)])
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_username, original_email, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username
        self.original_email = original_email

    def validate_username(self, username):
        if username.data != self.original_username:
            user = Account.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError(
                    _l('Please use a different username. This one is taken.'))

    def validate_email(self, email):
        if email.data != self.original_email:
            user = Account.query.filter_by(email=self.email.data).first()
            if user is not None:
                raise ValidationError(
                    _l('Please use a different email. This one is taken.'))


class DeleteProfileForm(FlaskForm):
    email = StringField(_l('Email'), validators=[DataRequired(), Email()])
    password = PasswordField(_l('Password'), validators=[DataRequired()])
    submit = SubmitField(_l('Submit'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app import db, mail
from app.main import bp
from flask import render_template, flash, redirect, url_for, request, g, jsonify, current_app
from flask_login import current_user, login_user, logout_user, login_required
from wtforms import SelectField
from app.main.forms import CreateCarForm, EditProfileForm, DeleteProfileForm
from app.models import Account, Car, Ride, coriders, ChatMessage
from app.translate import translate
from werkzeug.urls import url_parse
from datetime import datetime
from flask_babel import _, lazy_gettext as _l, get_locale
import os
from guess_language import guess_language


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
    g.locale = str(get_locale())


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    current_rides = Ride.query.join(coriders, coriders.c.ride_id == Ride.id).filter(
        coriders.c.account_id == current_user.id)
    req = request.args
    return render_template('main/index.html', title='Home', current_rides=current_rides, req=req)


@bp.route('/create_car', methods=['GET', 'POST'])
@login_required
def create_car():
    form = CreateCarForm()
    if form.validate_on_submit():
        car = Car(brand=form.brand.data,
                  model=form.model.data, color=form.color.data, owner=current_user)
        db.session.add(car)
        db.session.commit()
        flash(_('Your car has been created. Find it in your profile'))
        return redirect(url_for('main.index'))
    return render_template('main/create_car.html', title='Create Car', form=form)


@bp.route('/user/<username>', methods=['GET', 'POST'])
@login_required
def user(username):
    user = Account.query.filter_by(username=username).first_or_404()
    cars = Car.query.filter_by(owner_id=current_user.id)
    page = request.args.get('page', 1, type=int)
    req = request.args
    rides_as_driver = Ride.query.filter_by(driver=current_user.id).paginate(
        page, current_app.config['RIDES_PER_PAGE'], False)
    next_url = url_for('main.user', username=current_user.username, page=rides.next_num) \
        if rides_as_driver.has_next else None
    prev_url = url_for('main.user', username=current_user.username, page=rides.prev_num) \
        if rides_as_driver.has_prev else None
    return render_template('main/user.html', user=user,
                           cars=cars, rides_as_driver=rides_as_driver.items,
                           next_url=next_url, prev_url=prev_url)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username, current_user.email)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        db.session.commit()
        flash(_('Edited profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about_me.dat = current_user.about_me

    return render_template('main/edit_profile.html', form=form)


@bp.route('/delete_profile', methods=['GET', 'POST'])
@login_required
def delete_profile():
    form = DeleteProfileForm()
    if form.validate_on_submit():
        flash(_('Form valid'))
        if not current_user.email == form.email.data:
            flash('Enter YOUR email')
            return redirect(url_for('main.delete_profile'))
        else:
            user = Account.query.filter_by(email=form.email.data).first()

            if user.check_password(form.password.data):
                db.session.delete(current_user)
                db.session.commit()
                flash('Deleted account')
                return redirect(url_for('auth.register'))
            else:
                flash('Account can not be deleted using this credentials')
                return redirect(url_for('main.delete_profile'))
    return render_template('main/delete_profile.html', form=form)


@bp.route('/translate', methods=['POST'])
@login_required
def translate_text():
    return jsonify({'text': translate(request.form['text'],
                                      request.form['original_language'],
                                      request.form['target_language'])})

app/templates/main/create_car.html
{% extends 'base.html' %}
{% block app_content %}
    <h1> Create car </h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.brand.label }}
            {{ form.brand(size=32)}}
            {% for error in form.brand.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </p>
        <p>
            {{ form.model.label }}
            {{ form.model(size=32)}}
            {% for error in form.model.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </p>
        <p>
            {{ form.color.label }}
            {{ form.color(size=32)}}
            {% for error in form.color.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </p>
        <p>
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/main/delete_profile.html
{% extends 'base.html' %}

{% block app_content %}
    <h1> Delete your account permanently? </h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}
            {{ form.email(size=32)}}
            {% for error in form.email.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}
            {{ form.password(size=32)}}
            {% for error in form.password.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </p>
        <p>
            <p> You still can reregister </p>
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/main/edit_profile.html
{% extends 'base.html' %}
{% block app_content %}
    <h1> Edit Profile </h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{form.username.label}}
            {{form.username(size=40)}}
            {% for error in form.username.errors %}
                <span style="color: red;">{{error}}</span>
            {% endfor %}
        </p>
        <p>
            {{form.email.label}}
            {{form.email(size=40)}}
            {% for error in form.email.errors %}
                <span style="color: red;">{{error}}</span>
            {% endfor %}
        </p>
        <p>
            {{form.about_me.label}}
            {{form.about_me(size=40)}}
            {% for error in form.about_me.errors %}
                <span style="color: red;">{{error}}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% block app_content %}
<h1> Subscribed rides </h1>
    {% for ride in current_rides %}
    {% include '_ride.html' %} <br>
    {% endfor %}
{% endblock %}

app/templates/main/user.html
{% extends 'base.html' %}
{% block app_content %}

    <a href="{{url_for('main.edit_profile')}}"> Edit Profile </a>
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td><h1>User: {{ user.username }}</h1></td>
        </tr>
        <tr>
            <td>
                {% if user.last_seen %}
                    <p>Last seen on: {{ user.last_seen.strftime('%Y-%m-%d') }}</p>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>
                {% if user.about_me %}
                    {{ user.about_me }}
                {% endif %}
            </td>
            <td>
                {% if user.last_seen %}
                    <p>Member since: {{ user.member_since_utc.strftime('%Y-%m-%d') }}</p>
                {% endif %}
            </td>
        </tr>

    </table>
    <hr>
    <br>


    {% if cars != None %}
        <h3> Cars: </h3>
        {% for car in cars %}
            {% include '_car.html' %} <br>
        {% endfor %}
    {% endif %}

    {% if rides_as_driver != None %}
        <h3> Rides: </h3>
        {% for ride in rides_as_driver %}
            <p> Rides created by you: </p>
            <p>{{ride.from_location}} - {{ride.to_location}} - {{ride.ride_time}} </p>

        {% endfor %}
    {% endif %}
    {% if prev_url %}
            <a href="{{ prev_url }}">Newer rides</a>
    {% endif %}
    {% if next_url %}
            <a href="{{ next_url }}">Older rides</a>
    {% endif %}
    <br>
    <hr>

    <a href="{{url_for('main.delete_profile')}}"> Delete Profile </a>
{% endblock %}