app/ride/forms.py
from flask_wtf import FlaskForm
from flask_babel import _, lazy_gettext as _l
from wtforms import StringField, TextAreaField, SubmitField, DateTimeField, SelectField
from wtforms.validators import DataRequired, EqualTo, ValidationError, Email, Length
from app.models import Account
from flask_login import current_user


class CreateRideForm(FlaskForm):
    from_location = StringField(_l('Ride from'), validators=[DataRequired()])
    to_location = StringField(_l('Ride to'), validators=[DataRequired()])
    ride_time = DateTimeField(
        _l('Ride date and time'), format='%d-%m-%y %H:%M')
    cars = SelectField(_l('Car'), choices=[], validate_choice=False)
    free_seats = SelectField(
        _l('Seats'), choices=[1, 2, 3, 4, 5, 6], validate_choice=False)
    about_ride = TextAreaField(_l('About ride'))
    submit = SubmitField(_l('Submit'))


class ChatForm(FlaskForm):
    message = StringField(_l('Your message'), validators=[DataRequired()])
    submit = SubmitField(_l('Submit'))

app/ride/__init__.py
from flask import Blueprint

bp = Blueprint('ride', __name__)

from app.ride import routes

app/ride/routes.py
from app import db
from app.ride import bp
from flask import render_template, flash, redirect, url_for, request, g, jsonify, current_app
from flask_login import current_user, login_user, logout_user, login_required
from wtforms import SelectField
from app.ride.forms import CreateRideForm, ChatForm
from app.models import Account, Car, coriders, Ride, ChatMessage
from app.translate import translate
from werkzeug.urls import url_parse
from datetime import datetime
from flask_babel import _, lazy_gettext as _l, get_locale
import os
from app.email import send_email
from app.auth.email import send_password_reset_email
from guess_language import guess_language


@bp.route('/create_ride', methods=['GET', 'POST'])
@login_required
def create_ride():
    form = CreateRideForm()
    cars = Car.query.filter_by(owner_id=current_user.id).all()
    form.cars.choices = [(car.id, car.brand) for car in cars]
    if form.validate_on_submit():
        language = guess_language(form.about_ride.data)
        if language == 'UNKNOWN' or len(language) > 5:
            language = ''
        ride = Ride(driver=current_user.id,
                    car=form.cars.data,
                    from_location=form.from_location.data,
                    to_location=form.to_location.data,
                    ride_time=form.ride_time.data,
                    free_seats=form.free_seats.data,
                    about_ride=form.about_ride.data,
                    language=language)
        db.session.add(ride)
        db.session.commit()
        flash(_('Ride was created'))
        return redirect(url_for('ride.available_rides'))
    return render_template('ride/create_ride.html', form=form)


@bp.route('/available_rides', methods=['GET'])
@login_required
def available_rides():
    page = request.args.get('page', 1, type=int)
    req = request.args
    rides = Ride.query.filter(Ride.free_seats > 0).paginate(
        page, current_app.config['RIDES_PER_PAGE'], False)
    next_url = url_for('ride.available_rides', page=rides.next_num) \
        if rides.has_next else None
    prev_url = url_for('ride.available_rides', page=rides.prev_num) \
        if rides.has_prev else None
    return render_template('ride/available_rides.html',
                           rides=rides.items, next_url=next_url, prev_url=prev_url, req=req)


@bp.route('/subscribe_to_ride/<ride_id>', methods=['GET', 'POST'])
@login_required
def subscribe_to_ride(ride_id):
    ride = Ride.query.filter_by(id=ride_id).first()
    ride.free_seats -= 1
    ride.subscribe_to_ride(current_user)
    db.session.add(ride)
    db.session.commit()
    flash(_('Subscribed to ride'))
    return redirect(url_for('ride.chat', ride_id=ride.id))


@bp.route('/unsubscribe_from_ride/<ride_id>', methods=['GET', 'POST'])
@login_required
def unsubscribe_from_ride(ride_id):
    ride = Ride.query.filter_by(id=ride_id).first()
    ride.unsubscribe_from_ride(current_user)
    ride.free_seats += 1
    db.session.add(ride)
    db.session.commit()
    flash(_('Unsubscribed from ride'))
    return redirect(url_for('main.index'))


@bp.route('/chat/<ride_id>', methods=['GET', 'POST'])
@login_required
def chat(ride_id):
    form = ChatForm()
    ride = Ride.query.filter_by(id=ride_id).first()
    messages = ChatMessage.query.filter_by(ride_id=ride_id)
    if form.validate_on_submit():
        message = ChatMessage(
            ride_id=ride.id, content=form.message.data,
            user_posted=current_user.id,
            user_posted_username=current_user.username)
        db.session.add(message)
        db.session.commit()
    return render_template('ride/chat.html', ride=ride, form=form, messages=messages)

app/templates/_car.html
<table>
    <tr valign="top">
        <td><img src="{{ user.avatar(36) }}"></td>
        <td> <strong>{{car.brand}}</strong> {{ car.model }}</td>
    </tr>
</table>

app/templates/_ride.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">Ride from</th>
      <th scope="col">Ride to</th>
      <th scope="col">Ride time</th>
      <th scope="col">Free seats</th>
      <th scope="col">About ride</th>
      <th scope="col">Subscription</th>
      <th scope="col">Chat</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{ride.from_location}}</td>
      <td>{{ride.to_location}}</td>
      <td>{{ride.ride_time}}</td>
      <td>{{ride.free_seats}}</td>
      {% if ride.about_ride %}
        <td>{{ride.about_ride}}</td>
      {% else %}
        <td>{{_('Nothing was said about the ride yet.')}}</td>
      {% endif %}
      <td>
      {% if ride.is_subscribed(current_user) %}
            <a href="{{ url_for('ride.unsubscribe_from_ride', ride_id=ride.id)}}"> Unsubscribe from ride </a>
      {% elif ride.driver == current_user.id %}
            You created this ride
      {% else %}
            {% if ride.has_seats %}
                <a href="{{ url_for('ride.subscribe_to_ride', ride_id=ride.id)}}"> Subscribe to ride </a>
            {% else %}
                Ride has no seats left
            {% endif %}
      {% endif %}
      </td>
      <td>
      {% if ride.is_subscribed(current_user) %}
            <a href="{{ url_for('ride.chat', ride_id=ride.id)}}"> Chat</a>
      {% elif ride.driver == current_user.id %}
            <a href="{{url_for('ride.chat', ride_id=ride.id)}}"> Chat </a>
      {% else %}
            Subscribe first
      {% endif %}
      </td>
    </tr>
  </tbody>
</table>

app/templates/base.html
{% extends 'bootstrap/base.html' %}
<html>
    <head>
        {{ moment.include_jquery() }}
        {{ moment.include_moment() }}
        {{ moment.lang(g.locale) }}

        {% block scripts %}
        {{ super() }}
            <script>
            function translate(sourceElem, destElem, sourceLang, destLang) {
                $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
                $.post('/translate', {
                    text: $(sourceElem).text(),
                    original_language: sourceLang,
                    target_language: destLang
                }).done(function(response) {
                    $(destElem).text(response['text'])
                }).fail(function() {
                    $(destElem).text("{{ _('Error: Could not contact server.') }}");
                });
            }
            </script>
        {% endblock %}

        {% block title %}
            {% if title %}
                {{title}} - Ridesharing
            {% else %}
                Welcome to ridesharing
            {% endif %}
             Ridesharing
            {{current_user.username}}
        {% endblock %}
    </head>
    <body>
        {% block navbar %}
        <nav class="navbar navbar-default">
            <div>
                <a href="{{url_for('main.index')}}">Home</a>
                {% if current_user.is_anonymous %}
                    <a href=" {{ url_for('auth.login') }} "> {{_('Login')}} </a>
                    <a href=" {{ url_for('auth.register') }} "> {{_('Register')}} </a>
                {% else %}
                    <a href=" {{ url_for('main.user', username=current_user.username) }} "> Profile </a>
                    <a href=" {{ url_for('main.create_car') }} "> {{_('Create Car')}} </a> <br>
                    <a href=" {{ url_for('ride.available_rides') }}"> {{_('Available rides')}} </a>
                    <a href=" {{ url_for('ride.create_ride') }}"> {{_('Create ride')}} </a> <br>
                    <a href=" {{ url_for('auth.logout') }} "> {{_('Logout')}} </a>
                {% endif %}
            </div>
        </nav>
        {% endblock %}
        <hr>
        {% block content %}
            <div class="container">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info" role="alert">{{ message }}</div>
                    {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block app_content %}
                {% endblock %}
            </div>
        {% endblock %}
    </body>
</html>